export const books = [
  { id: 1, title: "The Hobbit", author: "J.R.R. Tolkien" },
  { id: 2, title: "1984", author: "George Orwell" },
  { id: 3, title: "To Kill a Mockingbird", author: "Harper Lee" },
  { id: 4, title: "Pride and Prejudice", author: "Jane Austen" },
  { id: 5, title: "The Catcher in the Rye", author: "J.D. Salinger" },
  { id: 6, title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
  { id: 7, title: "Moby Dick", author: "Herman Melville" },
  { id: 8, title: "Brave New World", author: "Aldous Huxley" },
  { id: 9, title: "Crime and Punishment", author: "Fyodor Dostoevsky" },
  { id: 10, title: "War and Peace", author: "Leo Tolstoy" },
  { id: 11, title: "The Brothers Karamazov", author: "Fyodor Dostoevsky" },
  { id: 12, title: "Jane Eyre", author: "Charlotte Brontë" },
  { id: 13, title: "Wuthering Heights", author: "Emily Brontë" },
  { id: 14, title: "The Lord of the Rings", author: "J.R.R. Tolkien" },
  { id: 15, title: "Anna Karenina", author: "Leo Tolstoy" },
  { id: 16, title: "Fahrenheit 451", author: "Ray Bradbury" },
  { id: 17, title: "Slaughterhouse-Five", author: "Kurt Vonnegut" },
  { id: 18, title: "The Alchemist", author: "Paulo Coelho" },
  { id: 19, title: "Frankenstein", author: "Mary Shelley" },
  { id: 20, title: "Dracula", author: "Bram Stoker" },
  { id: 21, title: "Les Misérables", author: "Victor Hugo" },
  { id: 22, title: "Don Quixote", author: "Miguel de Cervantes" },
  { id: 23, title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
  { id: 24, title: "The Count of Monte Cristo", author: "Alexandre Dumas" },
  { id: 25, title: "The Stranger", author: "Albert Camus" },
  { id: 26, title: "A Tale of Two Cities", author: "Charles Dickens" },
  { id: 27, title: "Great Expectations", author: "Charles Dickens" },
  { id: 28, title: "The Old Man and the Sea", author: "Ernest Hemingway" },
  { id: 29, title: "The Sun Also Rises", author: "Ernest Hemingway" },
  { id: 30, title: "The Grapes of Wrath", author: "John Steinbeck" }
];
